version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8888:8888"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/myMernApp
    links:
      - mongo
    depends_on:
      - mongo

  frontend:
    build: 
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - BACKEND_URL=http://backend:8888 # connect to backend docker port 8888
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
