version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8888:8888"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/myMernApp
    links:
      - mongo
    depends_on:
      - mongo

  frontend:
    build: 
      context: ./frontend
    ports:
      - "5173:5173"
    # links:
    #   - backend
    environment:
      DB_HOST: backend
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"