version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8888:8888"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/myMernApp
    links:
      - mongo
    depends_on:
      - mongo

  frontend:
    build: 
      context: ./frontend
    ports:
      - "5173:5173"
    # environment:
    #   DB_HOST: backend
    environment:
      - NODE_ENV=production   # 這裡可能需要設置你的應用程式的環境模式為生產模式
      - PROXY_TARGET=http://localhost:8888
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"