# frontend-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: ghcr.io/chingching17/frontend:latest
          ports:
            - containerPort: 5173
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: BACKEND_IP
              value: backend-clusterip
            - name: BACKEND_URL
              value: "http://$(BACKEND_IP):8888"
          livenessProbe:
            httpGet:
              path: /
              scheme: HTTP
              host: localhost
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
